version: '3.8'

services:

  localstack:
    restart: "no"
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_REGION=eu-north-1
      - AWS_DEFAULT_REGION=eu-north-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEBUG=1
  postgres:
    restart: "no"
    image: postgres:11.13
    ports:
      - "5432:5432"
    environment:
      - DEBUG=true
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catssrv
    volumes:
      - ./src/main/resources/:/docker-entrypoint-initdb.d/

