
    CREATE SCHEMA cats;
    CREATE TABLE IF NOT EXISTS "cats"."cat"
    (
        name character varying(50) COLLATE pg_catalog."default",
        id SERIAL  NOT NULL,
        weight integer,
        age integer,
        CONSTRAINT "cat_pkey" PRIMARY KEY (id)
    );

    CREATE TABLE IF NOT EXISTS "cats"."image"
    (
            id SERIAL  NOT NULL,
            cat_photo BYTEA,
            FOREIGN KEY (id)
            REFERENCES cats.cat (id)
            ON DELETE CASCADE
    );
    CREATE TABLE "cats"."jsonCat" (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR(255),
        attributes JSONB
    );